/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackButton: typeof import('./theme/components/BackButton.vue')['default']
    BookmarkItem: typeof import('./theme/components/BookmarkItem.vue')['default']
    BookmarkList: typeof import('./theme/pages/BookmarkList.vue')['default']
    BookmarksList: typeof import('./theme/pages/BookmarkList.vue')['default']
    DemoList: typeof import('./theme/pages/DemoList.vue')['default']
    Items: typeof import('./theme/components/Items.vue')['default']
    LinkButton: typeof import('./theme/components/LinkButton.vue')['default']
    List: typeof import('./theme/pages/List.vue')['default']
    NoteList: typeof import('./theme/pages/NoteList.vue')['default']
    OnlyTime: typeof import('./theme/components/OnlyTime.vue')['default']
    OnlyTitle: typeof import('./theme/components/OnlyTitle.vue')['default']
    PostList: typeof import('./theme/pages/PostList.vue')['default']
    ProjectItem: typeof import('./theme/components/ProjectItem.vue')['default']
    ProjectList: typeof import('./theme/pages/ProjectList.vue')['default']
    TalkList: typeof import('./theme/pages/TalkList.vue')['default']
    TimeTitle: typeof import('./theme/components/TimeTitle.vue')['default']
    TimeTItle: typeof import('./theme/components/TimeTitle.vue')['default']
    Title: typeof import('./theme/components/Title.vue')['default']
  }
}
