/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LinkButton: typeof import('./theme/components/LinkButton.vue')['default']
    List: typeof import('./theme/pages/List.vue')['default']
  }
}
