/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AnimatedUnocss: typeof import('./theme/components/icon/AnimatedUnocss.vue')['default']
    BackTop: typeof import('./theme/components/BackTop.vue')['default']
    BiliBili: typeof import('./components/BiliBili.vue')['default']
    Destyler: typeof import('./theme/components/icon/Destyler.vue')['default']
    Empty: typeof import('./theme/components/Empty.vue')['default']
    Footer: typeof import('./theme/components/Footer.vue')['default']
    Header: typeof import('./theme/components/Header.vue')['default']
    Icon: typeof import('./components/Icon.vue')['default']
    IconAnimatedUnocss: typeof import('./theme/components/icon/AnimatedUnocss.vue')['default']
    IconDestyler: typeof import('./theme/components/icon/Destyler.vue')['default']
    IconJumpIde: typeof import('./theme/components/icon/JumpIde.vue')['default']
    IconLivraison: typeof import('./theme/components/icon/Livraison.vue')['default']
    IconReactivityVue: typeof import('./theme/components/icon/ReactivityVue.vue')['default']
    IconTrends: typeof import('./theme/components/icon/Trends.vue')['default']
    JumpIde: typeof import('./theme/components/icon/JumpIde.vue')['default']
    Livraison: typeof import('./theme/components/icon/Livraison.vue')['default']
    Main: typeof import('./theme/components/Main.vue')['default']
    Pager: typeof import('./theme/components/Pager.vue')['default']
    ReactivityVue: typeof import('./theme/components/icon/ReactivityVue.vue')['default']
    SubNavBar: typeof import('./theme/components/SubNavBar.vue')['default']
    Title: typeof import('./theme/components/Title.vue')['default']
    Trends: typeof import('./theme/components/icon/Trends.vue')['default']
    Tweet: typeof import('./components/Tweet.vue')['default']
    YouTube: typeof import('./components/YouTube.vue')['default']
  }
}
