/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutData: typeof import('./../pages/about/Data.vue')['default']
    AboutPage: typeof import('./../pages/about/Page.vue')['default']
    AboutTitle: typeof import('./../pages/about/Title.vue')['default']
    BlockItem: typeof import('./../theme/components/BlockItem.vue')['default']
    BlogItem: typeof import('./components/blog/Item.vue')['default']
    BlogList: typeof import('./components/blog/List.vue')['default']
    BlogPage: typeof import('./../pages/blog/Page.vue')['default']
    BookmarksItem: typeof import('./components/bookmarks/Item.vue')['default']
    BookmarksList: typeof import('./components/bookmarks/List.vue')['default']
    BookmarksPage: typeof import('./../pages/bookmarks/Page.vue')['default']
    HomePage: typeof import('./../pages/home/Page.vue')['default']
    LayoutDefault: typeof import('./../theme/components/layout/Default.vue')['default']
    LineItem: typeof import('./../theme/components/LineItem.vue')['default']
    NotePage: typeof import('./../pages/note/Page.vue')['default']
    NotesPage: typeof import('./components/notes/Page.vue')['default']
    PageList: typeof import('./../theme/components/PageList.vue')['default']
    Phonetic: typeof import('./../theme/components/Phonetic.vue')['default']
    ProjectsItem: typeof import('./components/projects/Item.vue')['default']
    ProjectsList: typeof import('./components/projects/List.vue')['default']
    ProjectsPage: typeof import('./../pages/projects/Page.vue')['default']
    TalkPage: typeof import('./../pages/talk/Page.vue')['default']
    Title: typeof import('./../theme/components/Title.vue')['default']
  }
}
