export { default as AsideItem } from './components/AsideItem.vue'
export { default as Background } from './components/Background.vue'
export { default as CustomAside } from './components/CustomAside.vue'
export { default as CustomContent } from './components/CustomContent.vue'

export { default as About } from './components/icones/About.vue'
export { default as Blog } from './components/icones/Blog.vue'
export { default as Bookmarks } from './components/icones/Bookmarks.vue'
export { default as Discord } from './components/icones/Discord.vue'
export { default as Email } from './components/icones/Email.vue'
export { default as Gallery } from './components/icones/Gallery.vue'
export { default as GitHub } from './components/icones/GitHub.vue'
export { default as Instagram } from './components/icones/Instagram.vue'
export { default as Mastodon } from './components/icones/Mastodon.vue'
export { default as Note } from './components/icones/Note.vue'
export { default as Project } from './components/icones/Project.vue'
export { default as Signal } from './components/icones/Signal.vue'
export { default as Talk } from './components/icones/Talk.vue'
export { default as Twitter } from './components/icones/Twitter.vue'
export { default as Video } from './components/icones/Video.vue'

export * from './types/menu'
export * from './types/socialLink'
export * from './types/subscribeLink'
