/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/AboutPage.vue')['default']
    AboutPage: typeof import('./components/AboutPage.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
  }
}
